import { Link, useNavigate } from 'react-router-dom'
import { Button, ErrorState } from '../components/ui'
import { useAuth } from '../hooks/useAuth'
import { useState, type FormEvent } from 'react'

export function AuthPage({ mode }: { mode: 'login' | 'register' }) {
  const isLogin = mode === 'login'
  const { login, register, error, clearError } = useAuth(); const navigate = useNavigate(); const [values, setValues] = useState({ name: '', email: '', password: '', confirmPassword: '' }); const [validationError, setValidationError] = useState(''); const [isSubmitting, setIsSubmitting] = useState(false)
  function update(name: keyof typeof values, value: string) { setValues((current) => ({ ...current, [name]: value })); setValidationError(''); clearError() }
  function validate() { if (!values.email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.email)) return 'Enter a valid work email.'; if (!values.password) return 'Enter your password.'; if (!isLogin && values.name.trim().length < 2) return 'Enter your name.'; if (!isLogin && values.password.length < 8) return 'Password must be at least 8 characters.'; if (!isLogin && values.password !== values.confirmPassword) return 'Passwords do not match.'; return '' }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const message = validate(); if (message) { setValidationError(message); return }; setIsSubmitting(true); try { const authenticatedUser = isLogin ? await login(values.email, values.password) : await register(values.name.trim(), values.email, values.password); navigate(authenticatedUser.role.toLowerCase() === 'admin' ? '/admin/dashboard' : '/employee/dashboard', { replace: true }) } catch { /* AuthContext exposes the user-facing error. */ } finally { setIsSubmitting(false) } }
  return <main className="auth-page"><section className="auth-panel"><div className="brand">day<span>flow</span></div><div className="eyebrow">HRMS workspace</div><h1>{isLogin ? 'Welcome back' : 'Create your account'}</h1><p>{isLogin ? 'Sign in to continue to your workspace.' : 'Set up your employee workspace access.'}</p>{(validationError || error) && <ErrorState message={validationError || error || undefined} />}<form className="auth-form" onSubmit={submit} noValidate>{!isLogin && <label className="field-label">Full name<input required value={values.name} onChange={(event) => update('name', event.target.value)} name="name" autoComplete="name" /></label>}<label className="field-label">Work email<input required value={values.email} onChange={(event) => update('email', event.target.value)} type="email" name="email" autoComplete="email" /></label><label className="field-label">Password<input required value={values.password} onChange={(event) => update('password', event.target.value)} type="password" name="password" autoComplete={isLogin ? 'current-password' : 'new-password'} /></label>{!isLogin && <label className="field-label">Confirm password<input required value={values.confirmPassword} onChange={(event) => update('confirmPassword', event.target.value)} type="password" name="confirmPassword" autoComplete="new-password" /></label>}<Button disabled={isSubmitting} type="submit">{isSubmitting ? 'Working...' : isLogin ? 'Sign in' : 'Register'}</Button></form><Link className="auth-link" to={isLogin ? '/register' : '/login'}>{isLogin ? 'Need an account? Register' : 'Already have an account? Sign in'}</Link></section></main>
}